services:
  - type: web
    name: heading-harvester
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn harvester:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000 