services:
  - type: web
    name: heading-extractor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn harvester:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_KEY
        sync: false
